services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www
      - ./.docker/php/logs/:/var/log/
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: always
    networks:
      - php-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
        - php-network
    links:
        - php

networks:
  php-network:
    driver: bridge
